@url= http://localhost:3333

# @name Get all users
GET  {{url}}/users
###

# @name Create a new user
POST  {{url}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com"
}
###

# @name Delete a user
DELETE  {{url}}/users/691fa7cc-2266-41c1-9b63-d3e4c728c720
###