@url= http://localhost:3333

# @name Get all users
GET  {{url}}/users
###

# @name Create a new user
POST  {{url}}/users
Content-Type: application/json

{
  "name": "Matheus Viscki",
  "email": "example1@email.com"
}
###

# @name Put a user
PUT {{url}}/users/f819c9fa-6fca-49c8-9020-e99fcde788f9
Content-Type: application/json

{
  "name": "Matheus Igor",
  "email": "example2@email.com"
}
###

# @name Delete a user
DELETE  {{url}}/users/691fa7cc-2266-41c1-9b63-d3e4c728c720
###